name: WCA NR API

# Every day at 4:00 AM
on:
   schedule:
     - cron: "0 4 * * *"

# "Write" permissions, so that the workflow can push changes
permissions:
  contents: write

jobs:
  wca-nr-api-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Set up Python 3.13
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Execute the WCA NR API
    - name: Execute NR API
      env:
        WCA_COUNTRY: ${{ secrets.WCA_COUNTRY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        ROLE_ID: ${{ secrets.ROLE_ID }}
      run: |
        cd wca_nr_api
        python main.py
    # Get list of changed files
    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0
    # Push the new records.json file if it was changed during the API execution
    - name: Push If There Are Updated Records
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          if [[ "$file" == "wca_nr_api/storage/records.json" ]]; then
            git config --global user.name "ogi02"
            git config --global user.email "ogi02@users.noreply.github.com"
            git status
            git add wca_nr_api/storage/records.json
            git commit -m "Updated records"
            git push
          fi
        done
