name: WCA NR API

# on:
  # schedule:
    # - cron: "0 4 * * *"

on:
  push:
    branches:
      test-workflow

permissions:
  contents: write

jobs:
  wca-nr-api-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute NR API
      env:
        WCA_COUNTRY: ${{ secrets.WCA_COUNTRY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        ROLE_ID: ${{ secrets.ROLE_ID }}
      run: |
        cd wca_nr_api
        python main.py
    - name: Push Updated Records
      run: |
        git config --global user.name "ogi02"
        git config --global user.email "ogi02@users.noreply.github.com"
        git status
        git add storage/records.json
        git commit -m "Updated records"
        git push
