name: WCA NR API

# Every day at 2:00 AM
on:
  schedule:
    - cron: "0 2 * * *"

# On push to main "branch" - If needed for debugging
# on:
#   push:
#     branches:
#       - main

# "Write" permissions, so that the workflow can push changes
permissions:
  contents: write

jobs:
  wca-nr-api-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    # Set up Python 3.13
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Execute the WCA NR API
    - name: Execute NR API
      env:
        WCA_COUNTRY: ${{ secrets.WCA_COUNTRY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        ROLE_ID: ${{ secrets.ROLE_ID }}
      run: |
        cd wca_nr_api
        python main.py
    # Set up GitHub user for committing back changes
    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    # Check for changes in the file with records
    - name: Check For Changes
      run: |
        shopt -s nullglob
        files_to_add=(wca_nr_api/storage/records.json wca_nr_api/backup/records*)
        if [ ${#files_to_add[@]} -eq 0 ]; then
          echo "No files to add"
          exit 0
        fi
        git add "${files_to_add[@]}"
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
    # Commit and push changes
    - name: Commit & Push Changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git commit -m "GitHub Actions Workflow Updated Records"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
